[versions]
gradleplugin = "7.2.2"
kotlin = "1.7.10"

[libraries]
core-ktx = "androidx.core:core-ktx:1.9.0"
material = "com.google.android.material:material:1.7.0"
app-compat = "androidx.appcompat:appcompat:1.5.0"

# Firebase
firebase-bom = "com.google.firebase:firebase-bom:31.1.0"
firebase-auth = { module  ="com.google.firebase:firebase-auth-ktx" }

# Google
gson = "com.google.code.gson:gson:2.9.0"
google-services = "com.google.gms:google-services:4.3.14"

# Test
junit4 = "junit:junit:4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
